"""
Django settings for manager project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from pathlib import Path
import sys

from django.utils.translation import gettext_lazy as _
import environ


env = environ.Env()

BASE_DIR = Path(__file__).resolve().parent.parent.parent
APP_FOLDERS = ["apps", "lib"]

for folder in APP_FOLDERS:
    sys.path.insert(0, str(BASE_DIR / folder))

ALLOWED_HOSTS = []

env_file = Path(__file__).resolve().parent / ".env"
if env_file.exists():
    environ.Env.read_env(str(env_file))

SECRET_KEY = env("SECRET_KEY")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR / "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)


WSGI_APPLICATION = "manager.wsgi.application"


# Application definition

INSTALLED_APPS = [
    "admin_shortcuts",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "compressor",
    "rangefilter",
    "tenants",
    "bank_account",
    "bills",
]

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {"default": env.db()}

ADMIN_SHORTCUTS = [
    # Dummy shortcut. Balance title is hardcoded in the admin
    {"title": "Balance", "shortcuts": [{"title": "", "url": "/"}]},
    {
        "title": "Bills",
        "shortcuts": [
            {"title": "Add Bill", "url_name": "admin:bills_bill_add"},
            {"title": "Change Bills", "url_name": "admin:bills_bill_changelist"},
        ],
    },
    {
        "shortcuts": [
            {
                "title": "Change Tenant Bills",
                "url_name": "admin:bills_tenantvaluebill_changelist",
            },
            {
                "title": "Change Recurrent Bills",
                "url_name": "admin:bills_recurrentbill_changelist",
            },
        ]
    },
]

ADMIN_SHORTCUTS_SETTINGS = {
    "show_on_all_pages": True,
    "hide_app_list": True,
    "open_new_window": False,
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "pt"
LANGUAGES = (("pt", _("Portuguese")), ("en", _("English")))
LOCALE_PATHS = (os.path.join(BASE_DIR, "locale/"),)

TIME_ZONE = "Europe/Lisbon"
TIME_ZONE = "UTC"
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATICFILES_DIRS = [("site", str(Path(__file__).resolve().parent.parent / "static"))]
COMPRESS_PRECOMPILERS = (("text/x-sass", "django_libsass.SassCompiler"),)
LIBSASS_OUTPUT_STYLE = "compressed"
LIBSASS_SOURCEMAPS = True

MEDIA_ROOT = str(BASE_DIR.parent.parent / "media")
STATIC_ROOT = str(BASE_DIR.parent.parent / "static")
MEDIA_URL = "/media/"
STATIC_URL = "/static/"
