# Generated by Django 2.2.7 on 2019-11-09 01:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, help_text='Optional. Source can be used instead of name', max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, help_text='Value will be divided by the number of selected Tenants upon save', max_digits=9, verbose_name='Value')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='BillSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Bill Source',
                'verbose_name_plural': 'Bill Sources',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TenantValueBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.DecimalField(decimal_places=2, help_text='Value will be divided by the number of selected Tenants upon save', max_digits=9, verbose_name='Value')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant')),
            ],
            options={
                'verbose_name': 'Tenant Bill',
                'verbose_name_plural': 'Tenant Bills',
            },
        ),
        migrations.CreateModel(
            name='RecurrentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional. Source can be used instead of name', max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, help_text='Value will be divided by the number of selected Tenants upon save', max_digits=9, verbose_name='Value')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_start', models.DateField(help_text='Bills will be created starting from this             date and with a period set by Periodicity', verbose_name='Start Date')),
                ('periodicity', models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', max_length=100, verbose_name='Periodicity')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_recurrentbill_related', related_query_name='bills_recurrentbills', to='bills.BillSource', verbose_name='Bill Source')),
                ('tenants', models.ManyToManyField(help_text="The bill's total value is divided by the number of tenants", related_name='bills_recurrentbill_related', related_query_name='bills_recurrentbills', to='tenants.Tenant', verbose_name='Tenants')),
            ],
            options={
                'verbose_name': 'Recurrent Bill',
                'verbose_name_plural': 'Recurrent Bills',
                'ordering': ('active', 'date_start'),
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_bill_related', related_query_name='bills_bills', to='bills.BillSource', verbose_name='Bill Source'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tenants',
            field=models.ManyToManyField(help_text="The bill's total value is divided by the number of tenants", related_name='bills_bill_related', related_query_name='bills_bills', to='tenants.Tenant', verbose_name='Tenants'),
        ),
    ]
