# Generated by Django 3.2.13 on 2022-04-22 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Bill Source',
                'verbose_name_plural': 'Bill Sources',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RecurrentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional. Source can be used instead of name', max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Value')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_start', models.DateField(help_text='Bills will be created starting from this             date and with a period set by Periodicity', verbose_name='Start Date')),
                ('periodicity', models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', help_text='Ignore the day. Bills are generated in the first of every a month / year', max_length=100, verbose_name='Periodicity')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_recurrentbill_related', related_query_name='bills_recurrentbills', to='bills.billsource', verbose_name='Bill Source')),
                ('tenants', models.ManyToManyField(help_text="The bill's total value is divided by the number of tenants", related_name='bills_recurrentbill_related', related_query_name='bills_recurrentbills', to='tenants.Tenant', verbose_name='Tenants')),
            ],
            options={
                'verbose_name': 'Recurrent Bill',
                'verbose_name_plural': 'Recurrent Bills',
                'ordering': ('active', 'source', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, help_text='Optional. Source can be used instead of name', max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Value')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('paid', models.BooleanField(default=False, help_text="Merely indicative.<br> It doesn't mean the tenants paid it,             it means its transfer statement appeared in the bank.", verbose_name='Paid')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_bill_related', related_query_name='bills_bills', to='bills.billsource', verbose_name='Bill Source')),
                ('tenants', models.ManyToManyField(help_text="The bill's total value is divided by the number of tenants", related_name='bills_bill_related', related_query_name='bills_bills', to='tenants.Tenant', verbose_name='Tenants')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ('-date', 'source', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TenantValueBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.DecimalField(decimal_places=2, help_text='Value will be divided by the number of selected Tenants upon save', max_digits=9, verbose_name='Value')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Bill',
                'verbose_name_plural': 'Tenant Bills',
                'ordering': ('bill', 'tenant'),
                'unique_together': {('tenant', 'bill')},
            },
        ),
    ]
