# Generated by Django 2.2.7 on 2019-11-10 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('bills', '0002_auto_20191110_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ('-date', 'source', 'name'), 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantvaluebill',
            unique_together={('tenant', 'bill')},
        ),
    ]
