# Generated by Django 2.2.7 on 2019-11-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20191110_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False, help_text="Merely indicative.<br> It doesn't mean the tenants paid it,             it means its transfer statement appeared in the bank.", verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='recurrentbill',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Value'),
        ),
    ]
