# Generated by Django 2.2.7 on 2019-11-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
